module.exports = {
None:"I didn't get you.. Can you please brief out about your question.",
ITPortal:"In Informational Portal, you can view and download all the Commercial Taxes Department related information, Notifications, Acts, Rules, Forms and Tax application Process documents. In Transactional Portal, you can do all your taxation related activities like e-Registration, e-Payment, e-Returns, e-CST Forms Issuance etc.",
FTCPassword:"TNCTD Portal asks you to change the default generated password so that you can set the password of your own choice. It is also required to enable the secured access to your TNCTD Portal account. This security question and answer are essential for resetting of password in case you forget your password. We recommend that you set the secret question and answer known only to you. This would prevent chances of other user getting access to your TNCTD Portal account.",
ForgotPassword:"Click on the Forgot Password link on the transactional portal. If you are a registered dealer, then you can select any of the available two options : \n 1. Answer Security Question \n 2. Answer other details (only for registered dealers) and get your new password by entering required details. \n In case of users other than registered dealers, then select Answer Security Question and enter required details to get the new password.",
DealerSearch:"Both on the Informational Portal and Transactional portal has the link for Dealer Search. A dealer can be searched either by his TIN, PAN or Firm name.",
CommodityDetails:"Both on the Informational Portal and Transactional Portal has the link for Commodity Search & Tax Rates. User can search either by commodity name or by commodity code and click on search. All the details of the commodity will be displayed on the screen. \n A downloadable PDF file is also available containing the entire list and details of commodities.",
CanceledDealer:"On the TNCTD Portal homepage, click on the link List of cancelled dealers, enter the details and click on search. There is an option to export this list to excel as well.",
MapPractTransact:"The dealer can login to the Portal and click on the link Map Registered CA / CWA / VAT Practitioner under e-Services. Here he needs to enter the required details of CA / CWA / VAT Practitioner whom he wants to map and click on Map button.\n On TNCTD Web portal homepage, a link Know Your CA / CWA / VAT Practitioner is provided which displays all the registered CA / CWA / VAT Practitioners with TNCTD.",
ReportTaxEvasion:"In the Informational Portal, click on the link Report Tax Evasion, fill the relevant details and submit the complaint. \n The dealer can chose an option to reveal or not to reveal his identity.",
MacroSettingPopUp:"The user needs to enable the Macros in the excel sheet.",
MacroValidationError:"The user should click on Reset button which clears data and Reset Macro Validation for that sheet.",
ContactTNCTDHD:"On the TNCTD Portal homepage, Helpdesk Toll Free Number (18001036751) is displayed on top right corner. \n If the user has any doubt then he can post his query by clicking on the Request Logger link available on homepage. \n If the user wants to register any grievance then he can post his grievance by clicking on the Grievance Redressal link available on homepage. \n If the user has any suggestion then he can post his suggestion by clicking on the Suggestions link available on homepage. \n If the user wants to report any tax evasion incident then he can report such incident by clicking on the Report Tax Evasion link available on homepage."
};